import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Hamburguesa Trufada',
    description: 'Carne de res premium, queso brie, cebolla caramelizada y aceite de trufa.',
    price: 12.50,
    category: 'platos',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&q=80',
    available: true,
  },
  {
    id: '2',
    name: 'Pizza Margherita',
    description: 'Tomate San Marzano, mozzarella di bufala y albahaca fresca.',
    price: 10.00,
    category: 'platos',
    image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=500&q=80',
    available: true,
  },
  {
    id: '3',
    name: 'Ensalada César',
    description: 'Lechuga romana, croutons, parmesano y aderezo casero.',
    price: 8.50,
    category: 'platos',
    image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=500&q=80',
    available: false,
  },
  {
    id: '4',
    name: 'Tacos Al Pastor',
    description: 'Cerdo marinado, piña, cilantro y cebolla en tortilla de maíz.',
    price: 9.00,
    category: 'platos',
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=500&q=80',
    available: true,
  },
  {
    id: '5',
    name: 'Limonada de Coco',
    description: 'Refrescante mezcla de limón y crema de coco.',
    price: 4.50,
    category: 'bebidas',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&q=80',
    available: true,
  },
  {
    id: '6',
    name: 'Vino Tinto Reserva',
    description: 'Copa de vino tinto de la casa, selección especial.',
    price: 6.00,
    category: 'bebidas',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=500&q=80',
    available: true,
  },
  {
    id: '7',
    name: 'Cerveza Artesanal',
    description: 'IPA local con notas cítricas y amargor equilibrado.',
    price: 5.50,
    category: 'bebidas',
    image: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=500&q=80',
    available: true,
  },
  {
    id: '8',
    name: 'Tiramisú Clásico',
    description: 'Capas de bizcocho empapado en café y crema de mascarpone.',
    price: 7.00,
    category: 'postres',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500&q=80',
    available: true,
  },
  {
    id: '9',
    name: 'Cheesecake de Frutos Rojos',
    description: 'Tarta de queso cremosa con coulis de frambuesa y arándanos.',
    price: 6.50,
    category: 'postres',
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=500&q=80',
    available: true,
  },
  {
    id: '10',
    name: 'Brownie con Helado',
    description: 'Brownie de chocolate caliente con una bola de helado de vainilla.',
    price: 6.00,
    category: 'postres',
    image: 'https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=500&q=80',
    available: false,
  },
];
